Repository Timify-repo/Timify-server, pull requests merged in 2024-07, with the labels that each got.

#40 [Feature/37] 공부 분류/방법/장소 삭제 API 및 등록 개수 제한 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
  src/main/java/timify/com/study/repository/StudyMethodRepository.java
  src/main/java/timify/com/study/repository/StudyPlaceRepository.java
  src/main/java/timify/com/study/repository/StudyTypeRepository.java
Labels: :sparkles: feature

#43 [Feature/37] set 메소드 @Setter 어노테이션으로 대체
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
Labels: :sparkles: feature

#44 [Feature/41] 카카오 소셜로그인 및 회원가입 API 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/timify/com/auth/AuthController.java
  src/main/java/timify/com/auth/AuthService.java
  src/main/java/timify/com/auth/KakaoApiService.java
  src/main/java/timify/com/auth/TestController.java
  src/main/java/timify/com/auth/dto/AuthRequest.java
  src/main/java/timify/com/auth/dto/AuthResponse.java
  src/main/java/timify/com/auth/security/SecurityConfig.java
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/domain/Gender.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/study/StudyService.java
  src/main/resources/application.yml
  src/main/resources/static/images/kakao_login_medium_narrow.png
  src/main/resources/templates/accessToken.html
  src/main/resources/templates/login.html
Labels: :sparkles: feature

#46 :sparkles: [Feat]: 항목 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/timify/com/common/apiPayload/exception/handler/SubjectHandler.java
  src/main/java/timify/com/domain/StudyTime.java
  src/main/java/timify/com/domain/Todo.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/subject/SubjectController.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/subject/domain/SubjectStatus.java
  src/main/java/timify/com/subject/dto/SubjectRequest.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
  src/main/java/timify/com/subject/repository/SubjectRepository.java
Labels: :sparkles: feature

#49 [Feature/47] 회원 정보 수정 API 구현
  src/main/java/timify/com/TempController.java
  src/main/java/timify/com/auth/security/SecurityConfig.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/member/dto/MemberResponse.java
Labels: :sparkles: feature

#51 [Refactor/50] 기존 코드 리팩토링
  src/main/java/timify/com/auth/annotation/AuthMember.java
  src/main/java/timify/com/auth/annotation/AuthMemberArgumentResolver.java
  src/main/java/timify/com/auth/dto/AuthRequest.java
  src/main/java/timify/com/config/WebConfig.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/member/repository/MemberRepository.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/repository/StudyMethodRepository.java
  src/main/java/timify/com/study/repository/StudyPlaceRepository.java
  src/main/java/timify/com/study/repository/StudyTypeRepository.java
  src/main/java/timify/com/subject/SubjectController.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/dto/SubjectRequest.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#52 [Feature/48] 보관함 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/dto/StudyResponse.java
  src/main/java/timify/com/subject/SubjectController.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/subject/dto/SubjectRequest.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
Labels: :sparkles: feature

#54 [Refactor/53] Controller 인터페이스 추가 및 코드 컨벤션 적용
  src/main/java/timify/com/auth/annotation/AuthMemberArgumentResolver.java
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/timify/com/subject/SubjectController.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/controller/SubjectController.java
  src/main/java/timify/com/subject/controller/SubjectControllerImpl.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/subject/dto/SubjectRequest.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
  src/main/java/timify/com/subject/repository/SubjectRepository.java
Labels: :recycle: refactor

#57 [Refactor/56] 연관관계 메서드 수정
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/domain/Subject.java
Labels: :recycle: refactor

#59 [Refactor/50] member, study 도메인 리팩토링
  build.gradle
  src/main/java/timify/com/common/validation/NotBlankIfNotNull.java
  src/main/java/timify/com/common/validation/NotBlankIfNotNullValidator.java
  src/main/java/timify/com/common/validation/NotBlankJsonNullable.java
  src/main/java/timify/com/common/validation/NotBlankJsonNullableValidator.java
  src/main/java/timify/com/common/validation/PastJsonNullable.java
  src/main/java/timify/com/common/validation/PastJsonNullableValidator.java
  src/main/java/timify/com/common/validation/SizeJsonNullable.java
  src/main/java/timify/com/common/validation/SizeJsonNullableValidator.java
  src/main/java/timify/com/config/ObjectMapperConfig.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/controller/MemberController.java
  src/main/java/timify/com/member/controller/MemberControllerImpl.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/controller/StudyController.java
  src/main/java/timify/com/study/controller/StudyControllerImpl.java
Labels: :recycle: refactor

#60 [Refactor/58] 응답 DTO 수정 및 리턴값 변경
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/controller/SubjectController.java
  src/main/java/timify/com/subject/controller/SubjectControllerImpl.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
Labels: :recycle: refactor

#62 [Feature/55]: 할 일 API 구현 (등록, 삭제, 조회, 복사)
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/code/status/SuccessStatus.java
  src/main/java/timify/com/common/apiPayload/exception/handler/TodoHandler.java
  src/main/java/timify/com/domain/StudyTime.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/todo/TodoConverter.java
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/controller/TodoController.java
  src/main/java/timify/com/todo/controller/TodoControllerImpl.java
  src/main/java/timify/com/todo/domain/Todo.java
  src/main/java/timify/com/todo/domain/TodoStatus.java
  src/main/java/timify/com/todo/dto/TodoRequest.java
  src/main/java/timify/com/todo/dto/TodoResponse.java
  src/main/java/timify/com/todo/repository/TodoRepository.java
Labels: :sparkles: feature

#65 [Feature/45] 로그아웃 API 구현 및 ApiResponse 응답 변경, 회원가입API 수정
  src/main/java/timify/com/auth/AuthController.java
  src/main/java/timify/com/auth/jwt/RefreshToken.java
  src/main/java/timify/com/auth/jwt/RefreshTokenRepository.java
  src/main/java/timify/com/auth/jwt/RefreshTokenService.java
  src/main/java/timify/com/auth/security/CustomAccessDeniedHandler.java
  src/main/java/timify/com/auth/security/EntryPointUnauthorizedHandler.java
  src/main/java/timify/com/auth/security/JwtAuthenticationExceptionHandler.java
  src/main/java/timify/com/common/apiPayload/ApiResponse.java
  src/main/java/timify/com/common/apiPayload/exception/ExceptionAdvice.java
  src/main/java/timify/com/config/RedisConfig.java
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/member/dto/MemberRequest.java
Labels: :recycle: refactor, :sparkles: feature

#64 [Refactor/63] 항목 조회 API 수정 및 응답 DTO 수정
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/controller/SubjectController.java
  src/main/java/timify/com/subject/controller/SubjectControllerImpl.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
  src/main/java/timify/com/subject/repository/SubjectRepository.java
Labels: :recycle: refactor

#67 [Refactor/66] 항목 순서변경 API 수정
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/subject/SubjectService.java
Labels: :recycle: refactor

#69 [Fix/68] redis 배포환경 문제 해결
  .github/workflows/deploy.yml
  src/main/java/timify/com/config/RedisConfig.java
Labels: :bug: bug
