Repository Timify-repo/Timify-server, pull requests merged in 2024-06, with the labels that each got.

#26 [Feature/25] 공부 분류 등록 API 및 에러 처리 추가
  src/main/java/timify/com/auth/AuthController.java
  src/main/java/timify/com/auth/AuthService.java
  src/main/java/timify/com/auth/jwt/RefreshTokenService.java
  src/main/java/timify/com/auth/security/CustomUserDetailsService.java
  src/main/java/timify/com/auth/security/SecurityConfig.java
  src/main/java/timify/com/auth/security/SecurityUtil.java
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/exception/ExceptionAdvice.java
  src/main/java/timify/com/domain/MemberMission.java
  src/main/java/timify/com/domain/Notice.java
  src/main/java/timify/com/domain/StudyMethod.java
  src/main/java/timify/com/domain/StudyPlace.java
  src/main/java/timify/com/domain/StudyTime.java
  src/main/java/timify/com/domain/StudyType.java
  src/main/java/timify/com/domain/Subject.java
  src/main/java/timify/com/domain/Todo.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/member/dto/MemberResponse.java
  src/main/java/timify/com/member/repository/MemberRepository.java
  src/main/java/timify/com/member/repository/StudyTypeRepository.java
Labels: :sparkles: feature

#28 [Feature/27] 공부 분류 조회/수정 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/exception/handler/StudyHandler.java
  src/main/java/timify/com/domain/Todo.java
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/member/dto/MemberRequest.java
  src/main/java/timify/com/member/dto/MemberResponse.java
  src/main/java/timify/com/member/repository/StudyTypeRepository.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/StudyConverter.java
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/domain/CategoryStatus.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/dto/StudyResponse.java
  src/main/java/timify/com/study/repository/StudyTypeRepository.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#30 [Feature/29] 공부 방법 등록/조회/수정 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/StudyConverter.java
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/dto/StudyResponse.java
  src/main/java/timify/com/study/repository/StudyMethodRepository.java
Labels: :sparkles: feature

#32 [Feature/31] 공부 장소 관련 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/study/StudyController.java
  src/main/java/timify/com/study/StudyConverter.java
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/dto/StudyResponse.java
  src/main/java/timify/com/study/repository/StudyPlaceRepository.java
Labels: :sparkles: feature

#34 [Ci/23] rds 재설정
  .github/workflows/deploy.yml
Labels: :construction_worker: ci

#36 [Ci/35] CI/CD 환경변수 추가
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#39 [Fix/38] 회원가입 API 수정
  src/main/java/timify/com/member/MemberController.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/dto/MemberRequest.java
Labels: :bug: bug
