Repository Timify-repo/Timify-server, pull requests merged in 2024-08, with the labels that each got.

#74 [Refactor/72] 할 일 등록 API 수정 및 API Endpoint 변경
  src/main/java/timify/com/subject/controller/SubjectControllerImpl.java
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/controller/TodoController.java
  src/main/java/timify/com/todo/controller/TodoControllerImpl.java
Labels: :recycle: refactor

#76 [Feature/71] 홈화면 항목 조회 API 구현
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/studytime/domain/StudyTime.java
  src/main/java/timify/com/studytime/repository/StudyTimeRepository.java
  src/main/java/timify/com/subject/SubjectConverter.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/controller/SubjectController.java
  src/main/java/timify/com/subject/controller/SubjectControllerImpl.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/subject/dto/SubjectResponse.java
  src/main/java/timify/com/subject/repository/SubjectRepository.java
  src/main/java/timify/com/todo/domain/Todo.java
  src/main/java/timify/com/utils/DateTimeUtil.java
Labels: :sparkles: feature

#78 [Feat/77] 특정 항목의 할일 목록 조회 API 구현
  src/main/java/timify/com/subject/controller/SubjectController.java
  src/main/java/timify/com/todo/TodoConverter.java
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/controller/TodoController.java
  src/main/java/timify/com/todo/controller/TodoControllerImpl.java
  src/main/java/timify/com/todo/dto/TodoResponse.java
  src/main/java/timify/com/todo/repository/TodoRepository.java
Labels: :sparkles: feature

#79 [Feat/77] 특정 항목의 할일 목록 조회 API 응답값 수정
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/domain/Todo.java
  src/main/java/timify/com/todo/dto/TodoResponse.java
Labels: :recycle: refactor, :sparkles: feature

#80 [Feature] 몰입도 기록 API 구현
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/common/apiPayload/exception/handler/StudyTimeHandler.java
  src/main/java/timify/com/member/domain/Member.java
  src/main/java/timify/com/studytime/StudyTimeConverter.java
  src/main/java/timify/com/studytime/StudyTimeService.java
  src/main/java/timify/com/studytime/controller/StudyTimeController.java
  src/main/java/timify/com/studytime/controller/StudyTimeControllerImpl.java
  src/main/java/timify/com/studytime/domain/StudyTime.java
  src/main/java/timify/com/studytime/domain/StudyTimeGrade.java
  src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
  src/main/java/timify/com/studytime/dto/StudyTimeResponse.java
  src/main/java/timify/com/studytime/repository/StudyTimeRepository.java
  src/main/java/timify/com/subject/domain/Subject.java
  src/main/java/timify/com/todo/TodoConverter.java
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/controller/TodoController.java
  src/main/java/timify/com/todo/controller/TodoControllerImpl.java
  src/main/java/timify/com/todo/domain/Todo.java
  src/main/java/timify/com/todo/dto/TodoRequest.java
  src/main/java/timify/com/utils/DateTimeUtil.java
Labels: :sparkles: feature

#86 [Feat/85] 회원 탈퇴 API 구현 및 회원가입 jwt 에러 해결
  src/main/java/timify/com/auth/security/JwtAuthFilter.java
  src/main/java/timify/com/member/MemberService.java
  src/main/java/timify/com/member/controller/MemberController.java
  src/main/java/timify/com/member/controller/MemberControllerImpl.java
  src/main/java/timify/com/member/dto/MemberResponse.java
  src/main/java/timify/com/study/repository/StudyMethodRepository.java
  src/main/java/timify/com/study/repository/StudyPlaceRepository.java
  src/main/java/timify/com/study/repository/StudyTypeRepository.java
  src/main/java/timify/com/studytime/repository/StudyTimeRepository.java
  src/main/java/timify/com/todo/repository/TodoRepository.java
Labels: :bug: bug, :sparkles: feature

#87 [Refactor/81] 공부 분류/방법/장소에 isDefault 추가
  src/main/java/timify/com/study/StudyConverter.java
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/controller/StudyControllerImpl.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
  src/main/java/timify/com/study/dto/StudyRequest.java
  src/main/java/timify/com/study/dto/StudyResponse.java
Labels: :recycle: refactor

#88 [Refactor/81] 공부 분류/방법/장소 isDefault 수정 안되는 버그 해결
  src/main/java/timify/com/member/MemberConverter.java
  src/main/java/timify/com/study/StudyService.java
Labels: :recycle: refactor, :bug: bug

#92 [Feat/89] 공부 분류/방법/장소 순서 변경 API 구현 및 항목 조회 API 수정
  src/main/java/timify/com/study/StudyService.java
  src/main/java/timify/com/study/controller/StudyController.java
  src/main/java/timify/com/study/controller/StudyControllerImpl.java
  src/main/java/timify/com/study/domain/StudyMethod.java
  src/main/java/timify/com/study/domain/StudyPlace.java
  src/main/java/timify/com/study/domain/StudyType.java
  src/main/java/timify/com/subject/SubjectService.java
  src/main/java/timify/com/subject/controller/SubjectController.java
Labels: :recycle: refactor, :sparkles: feature

#96 [Refactor/95] 요구사항 변경으로 인한 코드 리팩토링
  src/main/java/timify/com/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/timify/com/studytime/StudyTimeService.java
  src/main/java/timify/com/studytime/controller/StudyTimeController.java
  src/main/java/timify/com/studytime/controller/StudyTimeControllerImpl.java
  src/main/java/timify/com/studytime/dto/StudyTimeRequest.java
  src/main/java/timify/com/studytime/dto/StudyTimeResponse.java
  src/main/java/timify/com/todo/TodoService.java
  src/main/java/timify/com/todo/controller/TodoController.java
  src/main/java/timify/com/todo/controller/TodoControllerImpl.java
  src/main/java/timify/com/todo/dto/TodoRequest.java
Labels: :recycle: refactor
